kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: stress-svc
  labels:
    app: stress-svc
    app.kubernetes.io/component: stress-svc
    app.kubernetes.io/instance: stress-svc
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: basic-stress-test-git-app
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: '11'
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: stress-svc
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
